---
- name: install kubernetes
  hosts: kubernetes
  tasks:
    - name: copy docker daemon.json 
      become: yes
      copy:
        src: files/daemon.json
        dest: /etc/docker/daemon.json
      register: daemon
    - name: restart docker daemon
      become: yes
      service:
        name: docker
        state: restarted
      when: daemon.changed

- name: install kubernetes
  hosts: docker_registry
  vars:
    docker_registry: "192.168.1.11:5000"
    k8_version: '1.22.4'
    k8_coredns_version: '1.7.0'
    k8_etcd_version: '3.4.13-0'
    k8_pause_version: '3.2'
    registry_project_dir: "{{ ansible_user_dir }}/registry"
    sources_path: "{{ registry_project_dir }}/images-tar"
    container_images:
      - busybox:1.30
      - 'k8s.gcr.io/pause:{{ k8_pause_version }}'
      - 'k8s.gcr.io/etcd:{{ k8_etcd_version }}'
      - 'k8s.gcr.io/coredns:{{ k8_coredns_version }}'
      - 'k8s.gcr.io/kube-apiserver:v{{ k8_version }}'
      - 'k8s.gcr.io/kube-controller-manager:v{{ k8_version }}'
      - 'k8s.gcr.io/kube-scheduler:v{{ k8_version }}'
      - 'k8s.gcr.io/kube-proxy:v{{ k8_version }}'
      - 'calico/node:v3.18.1'
      - 'calico/pod2daemon-flexvol:v3.18.1'
      - 'calico/cni:v3.18.1'
      - 'quay.io/coreos/flannel:v0.12.0'
      - 'calico/kube-controllers:v3.18.1'
      - 'kubernetesui/dashboard:v2.0.0'
      - 'kubernetesui/metrics-scraper:v1.0.4'
      - 'weaveworks/weave-kube:2.8.1'
      - 'weaveworks/weave-npc:2.8.1'
  tasks:
    - include_tasks: tasks/kubernetes/docker-registry.yml

- name: install kubernetes
  hosts: kubernetes
  tasks:
    - include_tasks: tasks/kubernetes/prepare_k8.yml

- name: kubernetes config
  hosts: masternodes
  tasks:
    - name: copy config
      copy:
        src: files/kubernetes/
        dest: /etc/kubernetes/
      loop:
        - audit.yaml