all:
  vars:
    scenario: kubernetes
  children:
    hyperv:
      hosts:
        hostone:
    virtualbox:
      hosts:
        hosttwo:
    kubernetes:
      children:
        masternodes:
          hosts:
            masternode:
        workernodes:
          hosts:
            workerone:
        gitlab:
          hosts:
            gitlab-server:
    # only install docker role for hosts in docker group
    docker:
      hosts:
        hostone:
        hosttwo:
