all:
  vars:
    scenario: kubernetes
  children:
    hyperv:
      hosts:
        hostone:
    virtualbox:
      hosts:
        hosttwo:
    kubernetes:
      children:
        masternodes:
          hosts:
            masternode:
        workernodes:
          hosts:
            workerone:
    docker_registry:
      hosts:
        masternode:
