---
provider: hyper-v
cpus: 2
memory: 16384
boot_timeout: 200
ansible_user: vagrant
box: "bento/ubuntu-20.04"
synced_folder: "~\\Documents"
network:
  net: "public_network"
  bridge: "Internet"

# virtual box customize opts #
gui: true
customize_opts:
  "--accelerate3d": "off"
  "--vrde": "off"
  "--memory": "{{ memory }}"

file_provision:
  "~\\.gitconfig": "~/.gitconfig"
  "~\\.ssh\\id_rsa": "~/.ssh/id_rsa"
  "~\\.ssh\\id_rsa.pub": "~/.ssh/id_rsa.pub"

shell_provision:
  - "sudo systemctl stop systemd-resolved"
  - "sudo systemctl disable systemd-resolved"
  - "sudo rm -rf /etc/resolv.conf"
  - "sudo echo nameserver 1.1.1.1 >> ~/resolv.conf"
  - "sudo mv ~/resolv.conf /etc/resolv.conf"
