---
provider: virtualbox
cpus: 2
memory: 4096
boot_timeout: 200
ansible_user: vagrant
box: "bento/ubuntu-20.04"

intnet: 
  ip: "192.168.1.13"

# virtual box customize opts #
gui: false
customize_opts:
  "--accelerate3d": "off"
  "--vrde": "off"

file_provision:
  "~/.ssh/id_rsa": "~/.ssh/id_rsa"
  "~/.ssh/id_rsa.pub": "~/.ssh/id_rsa.pub"

shell_provision:
  - "sudo resolvectl dns eth0 1.1.1.1"
  - "sudo resolvectl dns eth1 1.1.1.1"
